---
title: "scratch"
output: html_notebook
---

# Setup
```{r}
library('googledrive')
library('tidyverse')
library('glue')
```

Identify and download the Grid Tracker
```{r}
grid_tracker_link = 'https://docs.google.com/spreadsheets/d/12NiUpu28SOCQvQTrp17b592cMgOoCgelMQyE1PNZygU/edit?usp=sharing'
file_id = drive_get(as_id(grid_tracker_link))

grid_tracker_dir = glue("{getwd()}/grid_tracker.csv")

drive_download(
    as_id(file_id$id),
    path = grid_tracker_dir,
    overwrite=TRUE)

grid_tracker_df = read_csv(grid_tracker_dir) %>% 
  select(-c("State"))
```

```{r}
# transpose the grid_tracker_df into t_grid_df
t_grid_df = grid_tracker_df %>%
   tibble::rownames_to_column() %>%  
   pivot_longer(-rowname) %>% 
   pivot_wider(names_from=rowname, values_from=value)

colnames(t_grid_df) = c("name", grid_tracker_df %>% pull("postal"))
```

```{r}
col_rename <- function(state, df, t_grid_df){
  print(glue("operating {state}"))
  state_row = t_grid_df %>% pull(state)
  new_colnames = t_grid_df %>% pull(name)
  keep_cols = intersect(
    state_row, 
    colnames(df)
    )
  mask = match(keep_cols, state_row)
  temp = df %>% select(all_of(keep_cols))
  colnames(temp) = new_colnames[mask]
  print(glue("completed {state}"))
  return(temp %>% 
    mutate("postal" = state))
}
```


Identify the list of files that require merging:
(source:https://stackoverflow.com/questions/64687627/download-all-files-and-subdirectories-from-a-google-drive-directory-from-r)
```{r}
share_link = 'https://drive.google.com/drive/folders/1zoeLvd5flvvKFNMSmoRxYhE_LK_-19N5?usp=sharing'
folder_id = drive_get(as_id(share_link))
# find files in the folder
files = drive_ls(folder_id)
```

```{r}
temp_file_dir = glue("{getwd()}/temp.csv")
output_df = tibble()

for (i in seq_along(head(files$name))) {
  #list files
  drive_download(
    as_id(files[i,]$id),
    path = temp_file_dir,
    overwrite=TRUE)
  
  STATE = str_sub(files$name[i],1,2)
  df = read_csv(temp_file_dir, col_types = cols(.default = "c"))
  renamed_df = col_rename(STATE, df, t_grid_df)

  output_df = output_df %>% bind_rows(renamed_df)
}
```

Verify what the output looks like:
```{r}
colnames(output_df)
output_df$postal %>% unique()
```

Export the output dataset
```{r}
hr_ds_link = "https://drive.google.com/drive/folders/11JHEtDNBQaF5aMXkTAzRaaroJPKUtcbn?usp=sharing"
hr_ds_id = drive_get(as_id(hr_ds_link))

OUTPUT_DIR = glue("{getwd()}/total_hrcohort.csv.gz")
write_csv(output_df,  OUTPUT_DIR)

```

```{r}
drive_upload(OUTPUT_DIR, hr_ds_id, name = "total_hrcohort.csv.gz", overwrite = TRUE, verbose = TRUE)
```

